//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infotecs.MiniJournal.Application.ArticleServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticleData", Namespace="http://schemas.datacontract.org/2004/07/Infotecs.MiniJournal.Contracts")]
    [System.SerializableAttribute()]
    public partial class ArticleData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArticleServiceReference.IArticleService")]
    public interface IArticleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/GetAllArticles", ReplyAction="http://tempuri.org/IArticleService/GetAllArticlesResponse")]
        Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData[] GetAllArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/GetAllArticles", ReplyAction="http://tempuri.org/IArticleService/GetAllArticlesResponse")]
        System.Threading.Tasks.Task<Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData[]> GetAllArticlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/CreateArticle", ReplyAction="http://tempuri.org/IArticleService/CreateArticleResponse")]
        bool CreateArticle(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/CreateArticle", ReplyAction="http://tempuri.org/IArticleService/CreateArticleResponse")]
        System.Threading.Tasks.Task<bool> CreateArticleAsync(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/UpdateArticle", ReplyAction="http://tempuri.org/IArticleService/UpdateArticleResponse")]
        bool UpdateArticle(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/UpdateArticle", ReplyAction="http://tempuri.org/IArticleService/UpdateArticleResponse")]
        System.Threading.Tasks.Task<bool> UpdateArticleAsync(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/DeleteArticle", ReplyAction="http://tempuri.org/IArticleService/DeleteArticleResponse")]
        bool DeleteArticle(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/DeleteArticle", ReplyAction="http://tempuri.org/IArticleService/DeleteArticleResponse")]
        System.Threading.Tasks.Task<bool> DeleteArticleAsync(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArticleServiceChannel : Infotecs.MiniJournal.Application.ArticleServiceReference.IArticleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticleServiceClient : System.ServiceModel.ClientBase<Infotecs.MiniJournal.Application.ArticleServiceReference.IArticleService>, Infotecs.MiniJournal.Application.ArticleServiceReference.IArticleService {
        
        public ArticleServiceClient() {
        }
        
        public ArticleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData[] GetAllArticles() {
            return base.Channel.GetAllArticles();
        }
        
        public System.Threading.Tasks.Task<Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData[]> GetAllArticlesAsync() {
            return base.Channel.GetAllArticlesAsync();
        }
        
        public bool CreateArticle(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article) {
            return base.Channel.CreateArticle(article);
        }
        
        public System.Threading.Tasks.Task<bool> CreateArticleAsync(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article) {
            return base.Channel.CreateArticleAsync(article);
        }
        
        public bool UpdateArticle(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article) {
            return base.Channel.UpdateArticle(article);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateArticleAsync(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article) {
            return base.Channel.UpdateArticleAsync(article);
        }
        
        public bool DeleteArticle(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article) {
            return base.Channel.DeleteArticle(article);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteArticleAsync(Infotecs.MiniJournal.Application.ArticleServiceReference.ArticleData article) {
            return base.Channel.DeleteArticleAsync(article);
        }
    }
}
